//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WebBanGiay.Module.BusinessObjects.ORMDataModel1
{

    public partial class ChiTietGioHang : XPObject
    {
        int fID;
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }
        GioHang fGioHang;
        [Association(@"ChiTietGioHangReferencesGioHang")]
        public GioHang GioHang
        {
            get { return fGioHang; }
            set { SetPropertyValue<GioHang>(nameof(GioHang), ref fGioHang, value); }
        }
        SanPham fSanPham;
        [Association(@"ChiTietGioHangReferencesSanPham")]
        public SanPham SanPham
        {
            get { return fSanPham; }
            set { SetPropertyValue<SanPham>(nameof(SanPham), ref fSanPham, value); }
        }
        int fSoLuong;
        public int SoLuong
        {
            get { return fSoLuong; }
            set { SetPropertyValue<int>(nameof(SoLuong), ref fSoLuong, value); }
        }
        decimal fDonGia;
        public decimal DonGia
        {
            get { return fDonGia; }
            set { SetPropertyValue<decimal>(nameof(DonGia), ref fDonGia, value); }
        }
    }

}
