//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WebBanGiay.Module.BusinessObjects.ORMDataModel1
{

    public partial class ChiTietDonHang : XPObject
    {
        int fID;
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }
        DonHang fDonHang;
        [Association(@"ChiTietDonHangReferencesDonHang")]
        public DonHang DonHang
        {
            get { return fDonHang; }
            set { SetPropertyValue<DonHang>(nameof(DonHang), ref fDonHang, value); }
        }
        SanPham fSanPham;
        [Association(@"ChiTietDonHangReferencesSanPham")]
        public SanPham SanPham
        {
            get { return fSanPham; }
            set { SetPropertyValue<SanPham>(nameof(SanPham), ref fSanPham, value); }
        }
        int fSoLuong;
        public int SoLuong
        {
            get { return fSoLuong; }
            set { SetPropertyValue<int>(nameof(SoLuong), ref fSoLuong, value); }
        }
        decimal fDonGia;
        public decimal DonGia
        {
            get { return fDonGia; }
            set { SetPropertyValue<decimal>(nameof(DonGia), ref fDonGia, value); }
        }
    }

}
