//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WebBanGiay.Module.BusinessObjects.ORMDataModel1
{

    public partial class DonHang : XPObject
    {
        int fIDDonHang;
        public int IDDonHang
        {
            get { return fIDDonHang; }
            set { SetPropertyValue<int>(nameof(IDDonHang), ref fIDDonHang, value); }
        }
        KhachHang fKhachHang;
        [Association(@"DonHangReferencesKhachHang")]
        public KhachHang KhachHang
        {
            get { return fKhachHang; }
            set { SetPropertyValue<KhachHang>(nameof(KhachHang), ref fKhachHang, value); }
        }
        DateTime fNgay;
        public DateTime Ngay
        {
            get { return fNgay; }
            set { SetPropertyValue<DateTime>(nameof(Ngay), ref fNgay, value); }
        }
        string fTrangThai;
        public string TrangThai
        {
            get { return fTrangThai; }
            set { SetPropertyValue<string>(nameof(TrangThai), ref fTrangThai, value); }
        }
        [Association(@"ChiTietDonHangReferencesDonHang")]
        public XPCollection<ChiTietDonHang> ChiTietDonHangs { get { return GetCollection<ChiTietDonHang>(nameof(ChiTietDonHangs)); } }
    }

}
