//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WebBanGiay.Module.BusinessObjects.ORMDataModel1
{

    public partial class KhachHang : XPObject
    {
        int fIDKhachHang;
        public int IDKhachHang
        {
            get { return fIDKhachHang; }
            set { SetPropertyValue<int>(nameof(IDKhachHang), ref fIDKhachHang, value); }
        }
        string fTenKhachHang;
        public string TenKhachHang
        {
            get { return fTenKhachHang; }
            set { SetPropertyValue<string>(nameof(TenKhachHang), ref fTenKhachHang, value); }
        }
        string fEmail;
        public string Email
        {
            get { return fEmail; }
            set { SetPropertyValue<string>(nameof(Email), ref fEmail, value); }
        }
        string fDiaChi;
        public string DiaChi
        {
            get { return fDiaChi; }
            set { SetPropertyValue<string>(nameof(DiaChi), ref fDiaChi, value); }
        }
        string fSoDienThoai;
        public string SoDienThoai
        {
            get { return fSoDienThoai; }
            set { SetPropertyValue<string>(nameof(SoDienThoai), ref fSoDienThoai, value); }
        }
        string fGioiTinh;
        public string GioiTinh
        {
            get { return fGioiTinh; }
            set { SetPropertyValue<string>(nameof(GioiTinh), ref fGioiTinh, value); }
        }
        string fNgaySinh;
        public string NgaySinh
        {
            get { return fNgaySinh; }
            set { SetPropertyValue<string>(nameof(NgaySinh), ref fNgaySinh, value); }
        }
        [Association(@"GioHangReferencesKhachHang")]
        public XPCollection<GioHang> GioHangs { get { return GetCollection<GioHang>(nameof(GioHangs)); } }
        [Association(@"DonHangReferencesKhachHang")]
        public XPCollection<DonHang> DonHangs { get { return GetCollection<DonHang>(nameof(DonHangs)); } }
    }

}
