//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WebBanGiay.Module.BusinessObjects.ORMDataModel1
{

    public partial class NhaCungCap : XPObject
    {
        int fIDNCC;
        public int IDNCC
        {
            get { return fIDNCC; }
            set { SetPropertyValue<int>(nameof(IDNCC), ref fIDNCC, value); }
        }
        string fTenNCC;
        public string TenNCC
        {
            get { return fTenNCC; }
            set { SetPropertyValue<string>(nameof(TenNCC), ref fTenNCC, value); }
        }
        string fSDT;
        public string SDT
        {
            get { return fSDT; }
            set { SetPropertyValue<string>(nameof(SDT), ref fSDT, value); }
        }
        [Association(@"SanPhamReferencesNhaCungCap")]
        public XPCollection<SanPham> SanPhams { get { return GetCollection<SanPham>(nameof(SanPhams)); } }
    }

}
