//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WebBanGiay.Module.BusinessObjects.ORMDataModel1
{

    public partial class SanPham : XPObject
    {
        int fIDSanPham;
        public int IDSanPham
        {
            get { return fIDSanPham; }
            set { SetPropertyValue<int>(nameof(IDSanPham), ref fIDSanPham, value); }
        }
        string fTenSanPham;
        public string TenSanPham
        {
            get { return fTenSanPham; }
            set { SetPropertyValue<string>(nameof(TenSanPham), ref fTenSanPham, value); }
        }
        string fMoTa;
        public string MoTa
        {
            get { return fMoTa; }
            set { SetPropertyValue<string>(nameof(MoTa), ref fMoTa, value); }
        }
        decimal fGiaBan;
        public decimal GiaBan
        {
            get { return fGiaBan; }
            set { SetPropertyValue<decimal>(nameof(GiaBan), ref fGiaBan, value); }
        }
        DanhMuc fDanhMuc;
        [Association(@"SanPhamReferencesDanhMuc")]
        public DanhMuc DanhMuc
        {
            get { return fDanhMuc; }
            set { SetPropertyValue<DanhMuc>(nameof(DanhMuc), ref fDanhMuc, value); }
        }
        ThuongHieu fThuongHieu;
        [Association(@"SanPhamReferencesThuongHieu")]
        public ThuongHieu ThuongHieu
        {
            get { return fThuongHieu; }
            set { SetPropertyValue<ThuongHieu>(nameof(ThuongHieu), ref fThuongHieu, value); }
        }
        string fHinhAnh;
        public string HinhAnh
        {
            get { return fHinhAnh; }
            set { SetPropertyValue<string>(nameof(HinhAnh), ref fHinhAnh, value); }
        }
        string fSize;
        public string Size
        {
            get { return fSize; }
            set { SetPropertyValue<string>(nameof(Size), ref fSize, value); }
        }
        int fTonKho;
        public int TonKho
        {
            get { return fTonKho; }
            set { SetPropertyValue<int>(nameof(TonKho), ref fTonKho, value); }
        }
        NhaCungCap fNCC;
        [Association(@"SanPhamReferencesNhaCungCap")]
        public NhaCungCap NCC
        {
            get { return fNCC; }
            set { SetPropertyValue<NhaCungCap>(nameof(NCC), ref fNCC, value); }
        }
        [Association(@"ChiTietGioHangReferencesSanPham")]
        public XPCollection<ChiTietGioHang> ChiTietGioHangs { get { return GetCollection<ChiTietGioHang>(nameof(ChiTietGioHangs)); } }
        [Association(@"ChiTietDonHangReferencesSanPham")]
        public XPCollection<ChiTietDonHang> ChiTietDonHangs { get { return GetCollection<ChiTietDonHang>(nameof(ChiTietDonHangs)); } }
    }

}
